version: "3.9"
services:
  hadoop1:
    image: ${IMAGE_HDFS_FULL}
    hostname: hadoop1
    environment:
      # hdfs
      - DEFAULTFS=hdfs://hadoop1:8020
      - DFS_REPLICATION=2
      - RESOURCEMANAGER_HOSTNAME=hadoop1
      - WORKERS=hadoop2,hadoop3
      - HDFS_START=hdfsstartall
      # knox
      - KNOX_START=knoxstart
      # hive
      - HIVE_START=hivestart
      - mysql_host=mysql
      - mysql_port=3306
      - mysql_db=hive
      - mysql_user=root
      - mysql_pwd=root_HADOOP_123
    ports:
      - "8443:8443"
      - "8088:8088"
      - "50070:50070"
      - "10000:10000"
    depends_on:
      - hadoop2
      - hadoop3
      - mysql
  hadoop2:
    image: ${IMAGE_HDFS_FULL}
    hostname: hadoop2
    environment:
      - DEFAULTFS=hdfs://hadoop1:8020
      - DFS_REPLICATION=2
      - RESOURCEMANAGER_HOSTNAME=hadoop1
      - WORKERS=hadoop2,hadoop3
      - HDFS_START=hdfsnotstart
  hadoop3:
    image: ${IMAGE_HDFS_FULL}
    hostname: hadoop3
    environment:
      - DEFAULTFS=hdfs://hadoop1:8020
      - DFS_REPLICATION=2
      - RESOURCEMANAGER_HOSTNAME=hadoop1
      - WORKERS=hadoop2,hadoop3
      - HDFS_START=hdfsnotstart
  mysql:
    image: mysql:5.7
    ports:
      - "33307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_HADOOP_123

networks:
  my-hdfs-cluster: