version: "3.9"
services:
  master:
    image: ${IMAGE_SPARK}
    hostname: master
    ports:
      - "8080:8080"
      - "18080:18080"
    environment:
      - SPARK_MASTER_HOST=localhost
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_START=sparkstart
      - SPARK_MASTER_RPC_PORT=7077
      - SPARK_HISTORY_ENABLE=true