version: "3.9"
services:
  # zk singleton
  zookeeper:
    image: ${IMAGE_ZOOKEEPER}
    environment:
      - MODE=singleton
    ports:
      - "12181:2181"
  # kafka cluster
  kafka1:
    image: ${IMAGE_KAFKA}
    environment:
      - zookeeper_server=zookeeper:2181
      - MODE=cluster
      - ID=0
    ports:
      - "19092:9092"
    depends_on:
      - zookeeper
  kafka2:
    image: ${IMAGE_KAFKA}
    environment:
      - zookeeper_server=zookeeper:2181
      - MODE=cluster
      - ID=1
    ports:
      - "19093:9092"
    depends_on:
      - zookeeper
  kafka3:
    image: ${IMAGE_KAFKA}
    environment:
      - zookeeper_server=zookeeper:2181
      - MODE=cluster
      - ID=2
    ports:
      - "19094:9092"
    depends_on:
      - zookeeper
networks:
  my-kafka-cluster: