version: "3.9"
services:
  hadoop1:
    image: ${IMAGE_HDFS_FULL}
    hostname: hadoop1
    environment:
      # hdfs
      - DEFAULTFS=hdfs://hadoop1:8020
      - RESOURCEMANAGER_HOSTNAME=hadoop1
      - HDFS_START=hdfsstart
      - SUPERUSER=admin,root,hue
      # knox
      - KNOX_START=knoxstart
      # hive
      - HIVE_START=hivestart
      - mysql_host=mysql
      - mysql_port=3306
      - mysql_db=hive
      - mysql_user=root
      - mysql_pwd=root_HADOOP_123
    ports:
      - "8443:8443"
      - "8088:8088"
      - "50070:50070"
      - "10000:10000"
    depends_on:
      - mysql
  hue:
    image: ${IMAGE_HUE}
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=hue
      - MYSQL_USER=hue
      - MYSQL_PASSWORD=hue@Qwer123
      - HIVE_SERVER_HOST=hadoop1
      - DEFAULTFS=hdfs://hadoop1:8020
      - WEBHDFS_ADDRESS=hadoop1:50070
    ports:
      - "8281:8281"
    depends_on:
      - mysql
  mysql:
    image: ${IMAGE_MYSQL}
    ports:
      - "33306:3306"
    environment:
      - ROOT_PASSWORD=root_HADOOP_123
      - USER_DB=hue
      - USER_NAME=hue
      - USER_PASSWORD=hue@Qwer123