on:
  schedule:
  - cron: "0 3 * * 7"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build_dev_golang
        run: |
          GO_VERSION=1.19.5 VERSION=7 REPO=mzsmieli cmd=push platform=linux/amd64,linux/arm64 make build_dev_golang
          GO_VERSION=1.19.5 VERSION=8 REPO=mzsmieli cmd=push platform=linux/amd64,linux/arm64 make build_dev_golang
          GO_VERSION=1.18.10 VERSION=7 REPO=mzsmieli cmd=push platform=linux/amd64,linux/arm64 make build_dev_golang
          GO_VERSION=1.18.10 VERSION=8 REPO=mzsmieli cmd=push platform=linux/amd64,linux/arm64 make build_dev_golang
          GO_VERSION=1.17.13 VERSION=7 REPO=mzsmieli cmd=push platform=linux/amd64,linux/arm64 make build_dev_golang
          GO_VERSION=1.17.13 VERSION=8 REPO=mzsmieli cmd=push platform=linux/amd64,linux/arm64 make build_dev_golang
          GO_VERSION=1.16.15 VERSION=7 REPO=mzsmieli cmd=push platform=linux/amd64,linux/arm64 make build_dev_golang
          GO_VERSION=1.16.15 VERSION=8 REPO=mzsmieli cmd=push platform=linux/amd64,linux/arm64 make build_dev_golang
          GO_VERSION=1.20 VERSION=7 REPO=mzsmieli cmd=push platform=linux/amd64,linux/arm64 make build_dev_golang
          GO_VERSION=1.20 VERSION=8 REPO=mzsmieli cmd=push platform=linux/amd64,linux/arm64 make build_dev_golang